# Generated by Django 5.1.6 on 2025-03-02 21:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='bio',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
